name: Build
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: .NET build
      run: dotnet build
